version: "3.7"

services:
  prime-numbers-server:
    container_name: prime-numbers-server
    image: primenumbersserver:0.1.0
    ports:
      - 9090:9090
    environment:
      - GRPC_SERVER_HOST=localhost
      - GRPC_SERVER_HOST=9090

  proxy:
    container_name: proxy
    image: proxy:0.1.0
    ports:
      - 8080:8080
    environment:
      - HTTP_SERVER_HOST=localhost
      - HTTP_SERVER_PORT=8080
      - GRPC_CLIENT_HOST=prime-numbers-server
      - GRPC_CLIENT_HOST=9090