version: "3.7"

services:
  prime-numbers-server:
    container_name: prime-numbers-server
    image: primenumbersserver:0.1.6
    ports:
      - 9090:9090
    environment:
      - GRPC_SERVER_HOST=0.0.0.0
      - GRPC_SERVER_PORT=9090

  proxy:
    container_name: proxy
    image: proxy:0.1.4
    ports:
      - 8080:8080
    environment:
      - HTTP_SERVER_HOST=0.0.0.0
      - HTTP_SERVER_PORT=8080
      - GRPC_SERVER_HOST=prime-numbers-server
      - GRPC_SERVER_PORT=9090